import type { RecoverableRoadmap } from "@/lib/roadmap-storage";

export const DEMO_ROADMAP: RecoverableRoadmap = {
  id: "learnx-demo-nextjs-roadmap",
  userName: null,
  title: "Full-Stack Next.js Developer in 12 Weeks",
  description: "A practical, portfolio-first path from modern React fundamentals to production-ready Next.js applications with databases, authentication, testing, and deployment.",
  estimatedDuration: "12 weeks",
  careerInsights: {
    marketDemand: "High demand across SaaS, e-commerce, and product engineering teams",
    entrySalary: "$65,000–$95,000 USD annually in the United States",
    topRoles: ["Junior Full-Stack Developer", "Next.js Developer", "Frontend Engineer"],
  },
  updatedAt: "2026-10-05T00:00:00.000Z",
  milestones: [
    {
      id: "demo-nextjs-foundations",
      title: "Modern JavaScript and React Foundations",
      description: "Build confidence with components, props, state, hooks, asynchronous JavaScript, and accessible interface patterns.",
      duration: "Weeks 1–3",
      resourceLinks: [
        { title: "React: Learn", url: "https://react.dev/learn" },
        { title: "MDN JavaScript Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide" },
      ],
      topicDetails: null,
      example: null,
      interviewQuestions: [],
      exhaustiveDeepDive: "## Outcome\n\nBuild a responsive task dashboard using reusable React components and predictable state.\n\n## Practice\n\n- Model UI as a component tree.\n- Keep state close to the components that own it.\n- Add keyboard navigation and meaningful labels.\n- Fetch and render asynchronous data with loading and error states.\n\n## Portfolio checkpoint\n\nPublish the dashboard and document the component and state decisions in its README.",
      eli5Explanation: null,
      position: 1,
      isCompleted: true,
    },
    {
      id: "demo-nextjs-app-router",
      title: "Next.js App Router and Server Actions",
      description: "Learn layouts, server and client components, dynamic routes, caching, form actions, validation, and error boundaries.",
      duration: "Weeks 4–6",
      resourceLinks: [
        { title: "Next.js App Router", url: "https://nextjs.org/docs/app" },
        { title: "Next.js Server Actions", url: "https://nextjs.org/docs/app/getting-started/updating-data" },
      ],
      topicDetails: null,
      example: null,
      interviewQuestions: [],
      exhaustiveDeepDive: "## Outcome\n\nConvert the React dashboard into a full-stack Next.js application.\n\n## Practice\n\n- Render data in Server Components.\n- Isolate browser-only interaction in Client Components.\n- Validate mutations in Server Actions.\n- Add loading, not-found, and error boundaries.\n\n## Portfolio checkpoint\n\nExplain why each component runs on the server or client.",
      eli5Explanation: null,
      position: 2,
      isCompleted: false,
    },
    {
      id: "demo-nextjs-data-auth",
      title: "PostgreSQL, Drizzle, and Authentication",
      description: "Design relational data, write type-safe queries, protect mutations, and build secure credentials and OAuth flows.",
      duration: "Weeks 7–9",
      resourceLinks: [
        { title: "Drizzle ORM Documentation", url: "https://orm.drizzle.team/docs/overview" },
        { title: "Auth.js Documentation", url: "https://authjs.dev/getting-started" },
      ],
      topicDetails: null,
      example: null,
      interviewQuestions: [],
      exhaustiveDeepDive: "## Outcome\n\nAdd persistent users, projects, and permissions to the application.\n\n## Practice\n\n- Model one-to-many relationships.\n- Validate all untrusted input.\n- Authorize every server-side mutation.\n- Hash passwords and keep secrets server-only.\n\n## Portfolio checkpoint\n\nInclude an architecture diagram and a short security checklist.",
      eli5Explanation: null,
      position: 3,
      isCompleted: false,
    },
    {
      id: "demo-nextjs-production",
      title: "Testing, Performance, and Production Deployment",
      description: "Add automated tests, improve Core Web Vitals, monitor failures, and deploy a reliable production application.",
      duration: "Weeks 10–12",
      resourceLinks: [
        { title: "Next.js Testing", url: "https://nextjs.org/docs/app/guides/testing" },
        { title: "Vercel Deployment", url: "https://vercel.com/docs/deployments/overview" },
      ],
      topicDetails: null,
      example: null,
      interviewQuestions: [],
      exhaustiveDeepDive: "## Outcome\n\nShip a tested capstone with a repeatable deployment workflow.\n\n## Practice\n\n- Cover critical user journeys with browser tests.\n- Measure performance before optimizing.\n- Add structured error reporting.\n- Document environment variables and recovery steps.\n\n## Portfolio checkpoint\n\nRecord a two-minute product demo and publish a concise engineering case study.",
      eli5Explanation: null,
      position: 4,
      isCompleted: false,
    },
  ],
};
